title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/minima-plex"

show_excerpts: true # set to true to show excerpts on the homepage

favicon: "/assets/images/favicon.png"
favicon_svg: "/assets/images/favicon.svg"
apple_touch_icon: "/assets/images/apple-touch-icon.png"
permalink: pretty

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima-plex:
  skin: auto
  date_format: "%d %b %Y"

  # generate social links in footer
  social_links:
    - { platform: mastodon,       user_url: "https://masto.don/about" }
    - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
    - { platform: rss,            user_url: "/feed.xml" }
    - { platform: donate,         user_url: "https://opencollective.com/jekyll" }
    - { platform: bluesky,        user_url: "https://bsky.app/profile/bsky.app"}

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# Use `theme` if you want to install the theme directly or `remote_theme`
# to pull the theme from GitHub as part of the build process
remote_theme: questionlp/minima-plex

plugins:
 - jekyll-feed
 - jekyll-seo-tag
